### ISSUE TITLE
Updating To SDK v5.0

### ISSUE THREAD

**Issue by hybridmindset** [lilili87222/chartboost-ane-flash-air-android-ios#2]
Hi are you going to upgrade this ANE to v5.0 SDK?

**Comment by fix89** [comment]
Can you now update the ane for Version 5.1.2? I mean for iOS and Android... Thanks!

**Comment by BenoitFreslon** [comment]
+1 :) Thanks

**Comment by fix89** [comment]
An ETA please?

**Comment by lilili87222** [comment]
updated,add video ad,fix ios 8 rotation bug.

**Comment by lilili87222** [comment]
updated to 6.0
